
platform :ios, '7.0'

pod 'AttributedMarkdown', :git => 'https://github.com/dreamwieber/AttributedMarkdown.git'
pod 'JBChartView'
pod 'SORelativeDateTransformer'
pod 'SenseKit', :path => '../../SenseKit'

target 'Tests', :exclusive => true do
  pod 'Kiwi'
end
