
platform :ios, '7.0'

pod 'AttributedMarkdown', :git => 'https://github.com/dreamwieber/AttributedMarkdown.git'
pod 'JBChartView'
pod 'SORelativeDateTransformer'
pod 'SenseKit', :git => 'git@github.com:hello/SenseKit.git', :commit => '3946f358d54bc1556379dd0e3a3bec36bab363bc'

target 'Tests', :exclusive => true do
  pod 'Kiwi'
end
