//
//  HelloStyleKit.h
//  Sleep Sense
//
//  Created by Delisa Mason on 7/1/14.
//  Copyright (c) 2014 Hello. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@class PCGradient;

@interface HelloStyleKit : NSObject

// Colors
+ (UIColor*)darkBlueColor;
+ (UIColor*)mediumBlueColor;

// Gradients
+ (PCGradient*)blueBackgroundGradient;

// Drawing Methods
+ (void)drawCanvas1;

@end



@interface PCGradient : NSObject
@property(nonatomic, readonly) CGGradientRef CGGradient;
- (CGGradientRef)CGGradient NS_RETURNS_INNER_POINTER;

+ (instancetype)gradientWithColors: (NSArray*)colors locations: (const CGFloat*)locations;
+ (instancetype)gradientWithStartingColor: (UIColor*)startingColor endingColor: (UIColor*)endingColor;

@end
