//
//  HelloStyleKit.h
//  Sleep Sense
//
//  Created by Delisa Mason on 8/13/14.
//  Copyright (c) 2014 Hello. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@class PCGradient;

@interface HelloStyleKit : NSObject

// Colors
+ (UIColor*)darkBlueColor;
+ (UIColor*)mediumBlueColor;
+ (UIColor*)currentConditionsBackgroundColor;
+ (UIColor*)highSleepScoreColor;
+ (UIColor*)poorSleepScoreColor;
+ (UIColor*)averageSleepScoreColor;
+ (UIColor*)lightBlueColor;
+ (UIColor*)lightestBlueColor;

// Gradients
+ (PCGradient*)blueBackgroundGradient;

// Images
+ (UIImage*)alarmEnabledIcon;
+ (UIImage*)chevronIconLeft;
+ (UIImage*)alarmNoteIcon;
+ (UIImage*)questionIcon;
+ (UIImage*)settingsIcon;
+ (UIImage*)onboardingBackgroundImage1;
+ (UIImage*)onboardingBackgroundImage2;
+ (UIImage*)bluetoothLogoImage;
+ (UIImage*)worldMapImage;
+ (UIImage*)wifiLogoImage;
+ (UIImage*)humidityIcon;
+ (UIImage*)particleIcon;
+ (UIImage*)temperatureIcon;
+ (UIImage*)chevronIconRight;

// Drawing Methods
+ (void)drawSleepScoreGraphWithSleepScoreLabelText: (NSString*)sleepScoreLabelText sleepScore: (CGFloat)sleepScore sleepScoreDateText: (NSString*)sleepScoreDateText;
+ (void)drawMiniSleepScoreGraphWithSleepScore: (CGFloat)sleepScore;

@end



@interface PCGradient : NSObject
@property(nonatomic, readonly) CGGradientRef CGGradient;
- (CGGradientRef)CGGradient NS_RETURNS_INNER_POINTER;

+ (instancetype)gradientWithColors: (NSArray*)colors locations: (const CGFloat*)locations;
+ (instancetype)gradientWithStartingColor: (UIColor*)startingColor endingColor: (UIColor*)endingColor;

@end
