//
// HEMMainStoryboard.m
// Copyright (c) 2014 Hello Inc. All rights reserved.
// Generated by Ovaltine - http://github.com/kattrali/ovaltine

#import <UIKit/UIKit.h>
#import "HEMMainStoryboard.h"

static UIStoryboard *_storyboard = nil;
static NSString *const _HEMmain = @"Main";
static NSString *const _HEMalarmChoiceCell = @"alarmChoiceCell";
static NSString *const _HEMalarmListCellIdentifier = @"alarmListCellIdentifier";
static NSString *const _HEMalarmListViewController = @"alarmListViewController";
static NSString *const _HEMalarmNavController = @"alarmNavController";
static NSString *const _HEMalarmRepeat = @"alarmRepeat";
static NSString *const _HEMalarmRepeatTableViewController = @"alarmRepeatTableViewController";
static NSString *const _HEMalarmSoundTableViewController = @"alarmSoundTableViewController";
static NSString *const _HEMalarmViewController = @"alarmViewController";
static NSString *const _HEMcurrentConditionsCell = @"currentConditionsCell";
static NSString *const _HEMcurrentNavController = @"currentNavController";
static NSString *const _HEMdeviceCell = @"deviceCell";
static NSString *const _HEMdevicesSettings = @"devicesSettings";
static NSString *const _HEMfirmwareUpdateCell = @"firmwareUpdateCell";
static NSString *const _HEMinfo = @"info";
static NSString *const _HEMinfoSettings = @"infoSettings";
static NSString *const _HEMinsightCell = @"insightCell";
static NSString *const _HEMnoSleepPill = @"noSleepPill";
static NSString *const _HEMnoSleepPillController = @"noSleepPillController";
static NSString *const _HEMpersonalInfo = @"personalInfo";
static NSString *const _HEMpickSoundSegue = @"pickSoundSegue";
static NSString *const _HEMpill = @"pill";
static NSString *const _HEMpillInfoCell = @"pillInfoCell";
static NSString *const _HEMsense = @"sense";
static NSString *const _HEMsenseInfoCell = @"senseInfoCell";
static NSString *const _HEMsensorViewController = @"sensorViewController";
static NSString *const _HEMsettingsCell = @"settingsCell";
static NSString *const _HEMsettingsController = @"settingsController";
static NSString *const _HEMsettingsNavController = @"settingsNavController";
static NSString *const _HEMshowInsight = @"showInsight";
static NSString *const _HEMsingle = @"single";
static NSString *const _HEMsleepGraphController = @"sleepGraphController";
static NSString *const _HEMsleepGraphNavController = @"sleepGraphNavController";
static NSString *const _HEMsleepHistoryController = @"sleepHistoryController";
static NSString *const _HEMsleepQuestions = @"sleepQuestions";
static NSString *const _HEMtimeSliceCell = @"timeSliceCell";
static NSString *const _HEMunitCell = @"unitCell";
static NSString *const _HEMunitsSettings = @"unitsSettings";

@implementation HEMMainStoryboard

+(UIStoryboard *)storyboard { return _storyboard ?: (_storyboard = [UIStoryboard storyboardWithName:_HEMmain bundle:[NSBundle mainBundle]]); }

/** Cell Reuse Identifiers */
+(NSString *)alarmChoiceCellReuseIdentifier { return _HEMalarmChoiceCell; }
+(NSString *)alarmListCellIdentifier { return _HEMalarmListCellIdentifier; }
+(NSString *)currentConditionsCellReuseIdentifier { return _HEMcurrentConditionsCell; }
+(NSString *)deviceCellReuseIdentifier { return _HEMdeviceCell; }
+(NSString *)firmwareUpdateCellReuseIdentifier { return _HEMfirmwareUpdateCell; }
+(NSString *)infoReuseIdentifier { return _HEMinfo; }
+(NSString *)insightCellReuseIdentifier { return _HEMinsightCell; }
+(NSString *)pillInfoCellReuseIdentifier { return _HEMpillInfoCell; }
+(NSString *)senseInfoCellReuseIdentifier { return _HEMsenseInfoCell; }
+(NSString *)settingsCellReuseIdentifier { return _HEMsettingsCell; }
+(NSString *)singleReuseIdentifier { return _HEMsingle; }
+(NSString *)timeSliceCellReuseIdentifier { return _HEMtimeSliceCell; }
+(NSString *)unitCellReuseIdentifier { return _HEMunitCell; }

/** Segue Identifiers */
+(NSString *)alarmRepeatSegueIdentifier { return _HEMalarmRepeat; }
+(NSString *)devicesSettingsSegueIdentifier { return _HEMdevicesSettings; }
+(NSString *)infoSettingsSegueIdentifier { return _HEMinfoSettings; }
+(NSString *)noSleepPillSegueIdentifier { return _HEMnoSleepPill; }
+(NSString *)pickSoundSegueSegueIdentifier { return _HEMpickSoundSegue; }
+(NSString *)pillSegueIdentifier { return _HEMpill; }
+(NSString *)senseSegueIdentifier { return _HEMsense; }
+(NSString *)showInsightSegueIdentifier { return _HEMshowInsight; }
+(NSString *)unitsSettingsSegueIdentifier { return _HEMunitsSettings; }

/** View Controllers */
+(UIViewController *)instantiateAlarmListViewController { return [[self storyboard] instantiateViewControllerWithIdentifier:_HEMalarmListViewController]; }
+(UIViewController *)instantiateAlarmNavController { return [[self storyboard] instantiateViewControllerWithIdentifier:_HEMalarmNavController]; }
+(UIViewController *)instantiateAlarmRepeatTableViewController { return [[self storyboard] instantiateViewControllerWithIdentifier:_HEMalarmRepeatTableViewController]; }
+(UIViewController *)instantiateAlarmSoundTableViewController { return [[self storyboard] instantiateViewControllerWithIdentifier:_HEMalarmSoundTableViewController]; }
+(UIViewController *)instantiateAlarmViewController { return [[self storyboard] instantiateViewControllerWithIdentifier:_HEMalarmViewController]; }
+(UIViewController *)instantiateCurrentNavController { return [[self storyboard] instantiateViewControllerWithIdentifier:_HEMcurrentNavController]; }
+(UIViewController *)instantiateNoSleepPillController { return [[self storyboard] instantiateViewControllerWithIdentifier:_HEMnoSleepPillController]; }
+(UIViewController *)instantiatePersonalInfoViewController { return [[self storyboard] instantiateViewControllerWithIdentifier:_HEMpersonalInfo]; }
+(UIViewController *)instantiateSensorViewController { return [[self storyboard] instantiateViewControllerWithIdentifier:_HEMsensorViewController]; }
+(UIViewController *)instantiateSettingsController { return [[self storyboard] instantiateViewControllerWithIdentifier:_HEMsettingsController]; }
+(UIViewController *)instantiateSettingsNavController { return [[self storyboard] instantiateViewControllerWithIdentifier:_HEMsettingsNavController]; }
+(UIViewController *)instantiateSleepGraphController { return [[self storyboard] instantiateViewControllerWithIdentifier:_HEMsleepGraphController]; }
+(UIViewController *)instantiateSleepGraphNavController { return [[self storyboard] instantiateViewControllerWithIdentifier:_HEMsleepGraphNavController]; }
+(UIViewController *)instantiateSleepHistoryController { return [[self storyboard] instantiateViewControllerWithIdentifier:_HEMsleepHistoryController]; }
+(UIViewController *)instantiateSleepQuestionsViewController { return [[self storyboard] instantiateViewControllerWithIdentifier:_HEMsleepQuestions]; }

@end
