//
// HEMMainStoryboard.m
// Copyright (c) 2016 Hello Inc. All rights reserved.
// Generated by Ovaltine - http://github.com/kattrali/ovaltine

#import <UIKit/UIKit.h>
#import "HEMMainStoryboard.h"

static UIStoryboard *_storyboard = nil;
static NSString *const _HEMmain = @"Main";
static NSString *const _HEMrootViewController = @"RootViewController";
static NSString *const _HEMabout = @"about";
static NSString *const _HEMactionSheetViewController = @"actionSheetViewController";
static NSString *const _HEMalarmDeleteCell = @"alarmDeleteCell";
static NSString *const _HEMalarmExpansionCell = @"alarmExpansionCell";
static NSString *const _HEMalarmListCell = @"alarmListCell";
static NSString *const _HEMalarmListEmptyCell = @"alarmListEmptyCell";
static NSString *const _HEMalarmListNavViewController = @"alarmListNavViewController";
static NSString *const _HEMalarmListStatusCell = @"alarmListStatusCell";
static NSString *const _HEMalarmListViewController = @"alarmListViewController";
static NSString *const _HEMalarmNavController = @"alarmNavController";
static NSString *const _HEMalarmRepeat = @"alarmRepeat";
static NSString *const _HEMalarmRepeatCell = @"alarmRepeatCell";
static NSString *const _HEMalarmSoundCell = @"alarmSoundCell";
static NSString *const _HEMalarmSounds = @"alarmSounds";
static NSString *const _HEMalarmSwitchCell = @"alarmSwitchCell";
static NSString *const _HEMalarmViewController = @"alarmViewController";
static NSString *const _HEMbar = @"bar";
static NSString *const _HEMbreakdownController = @"breakdownController";
static NSString *const _HEMbreakdownLineCell = @"breakdownLineCell";
static NSString *const _HEMbubbles = @"bubbles";
static NSString *const _HEMcalendar = @"calendar";
static NSString *const _HEMchart = @"chart";
static NSString *const _HEMcommandGroup = @"commandGroup";
static NSString *const _HEMcommands = @"commands";
static NSString *const _HEMconfiguration = @"configuration";
static NSString *const _HEMcurrentNavController = @"currentNavController";
static NSString *const _HEMcurrentValue = @"currentValue";
static NSString *const _HEMdetail = @"detail";
static NSString *const _HEMerror = @"error";
static NSString *const _HEMexamples = @"examples";
static NSString *const _HEMexpansionConfig = @"expansionConfig";
static NSString *const _HEMfeed = @"feed";
static NSString *const _HEMfeedContainer = @"feedContainer";
static NSString *const _HEMgroup = @"group";
static NSString *const _HEMimage = @"image";
static NSString *const _HEMinfoCell = @"infoCell";
static NSString *const _HEMinfoNavigationController = @"infoNavigationController";
static NSString *const _HEMinfoViewController = @"infoViewController";
static NSString *const _HEMinsight = @"insight";
static NSString *const _HEMinsights = @"insights";
static NSString *const _HEMinsightsFeed = @"insightsFeed";
static NSString *const _HEMlist = @"list";
static NSString *const _HEMlistItem = @"listItem";
static NSString *const _HEMloading = @"loading";
static NSString *const _HEMmessage = @"message";
static NSString *const _HEMmultiple = @"multiple";
static NSString *const _HEMoption = @"option";
static NSString *const _HEMpair = @"pair";
static NSString *const _HEMquestion = @"question";
static NSString *const _HEMscale = @"scale";
static NSString *const _HEMsensor = @"sensor";
static NSString *const _HEMsettings = @"settings";
static NSString *const _HEMsingle = @"single";
static NSString *const _HEMsleepGraphController = @"sleepGraphController";
static NSString *const _HEMsleepHistoryController = @"sleepHistoryController";
static NSString *const _HEMsleepInsight = @"sleepInsight";
static NSString *const _HEMsleepQuestions = @"sleepQuestions";
static NSString *const _HEMsleepSound = @"sleepSound";
static NSString *const _HEMslideContainer = @"slideContainer";
static NSString *const _HEMsoundsNavigation = @"soundsNavigation";
static NSString *const _HEMsummary = @"summary";
static NSString *const _HEMsummaryViewCell = @"summaryViewCell";
static NSString *const _HEMtimeSliceCell = @"timeSliceCell";
static NSString *const _HEMtimelineFeedback = @"timelineFeedback";
static NSString *const _HEMtitle = @"title";
static NSString *const _HEMtoggle = @"toggle";
static NSString *const _HEMtrends = @"trends";
static NSString *const _HEMtutorialViewController = @"tutorialViewController";
static NSString *const _HEMvoice = @"voice";
static NSString *const _HEMwelcome = @"welcome";

@implementation HEMMainStoryboard

+(UIStoryboard *)storyboard { return _storyboard ?: (_storyboard = [UIStoryboard storyboardWithName:_HEMmain bundle:[NSBundle mainBundle]]); }

/** Cell Reuse Identifiers */
+(NSString *)aboutReuseIdentifier { return _HEMabout; }
+(NSString *)alarmDeleteCellReuseIdentifier { return _HEMalarmDeleteCell; }
+(NSString *)alarmExpansionCellReuseIdentifier { return _HEMalarmExpansionCell; }
+(NSString *)alarmListCellReuseIdentifier { return _HEMalarmListCell; }
+(NSString *)alarmListEmptyCellReuseIdentifier { return _HEMalarmListEmptyCell; }
+(NSString *)alarmListStatusCellReuseIdentifier { return _HEMalarmListStatusCell; }
+(NSString *)alarmRepeatCellReuseIdentifier { return _HEMalarmRepeatCell; }
+(NSString *)alarmSoundCellReuseIdentifier { return _HEMalarmSoundCell; }
+(NSString *)alarmSwitchCellReuseIdentifier { return _HEMalarmSwitchCell; }
+(NSString *)barReuseIdentifier { return _HEMbar; }
+(NSString *)breakdownLineCellReuseIdentifier { return _HEMbreakdownLineCell; }
+(NSString *)bubblesReuseIdentifier { return _HEMbubbles; }
+(NSString *)calendarReuseIdentifier { return _HEMcalendar; }
+(NSString *)chartReuseIdentifier { return _HEMchart; }
+(NSString *)commandGroupReuseIdentifier { return _HEMcommandGroup; }
+(NSString *)commandsReuseIdentifier { return _HEMcommands; }
+(NSString *)configurationReuseIdentifier { return _HEMconfiguration; }
+(NSString *)currentValueReuseIdentifier { return _HEMcurrentValue; }
+(NSString *)detailReuseIdentifier { return _HEMdetail; }
+(NSString *)errorReuseIdentifier { return _HEMerror; }
+(NSString *)examplesReuseIdentifier { return _HEMexamples; }
+(NSString *)groupReuseIdentifier { return _HEMgroup; }
+(NSString *)imageReuseIdentifier { return _HEMimage; }
+(NSString *)infoCellReuseIdentifier { return _HEMinfoCell; }
+(NSString *)insightReuseIdentifier { return _HEMinsight; }
+(NSString *)listItemReuseIdentifier { return _HEMlistItem; }
+(NSString *)loadingReuseIdentifier { return _HEMloading; }
+(NSString *)messageReuseIdentifier { return _HEMmessage; }
+(NSString *)multipleReuseIdentifier { return _HEMmultiple; }
+(NSString *)optionReuseIdentifier { return _HEMoption; }
+(NSString *)pairReuseIdentifier { return _HEMpair; }
+(NSString *)questionReuseIdentifier { return _HEMquestion; }
+(NSString *)scaleReuseIdentifier { return _HEMscale; }
+(NSString *)sensorReuseIdentifier { return _HEMsensor; }
+(NSString *)settingsReuseIdentifier { return _HEMsettings; }
+(NSString *)singleReuseIdentifier { return _HEMsingle; }
+(NSString *)summaryReuseIdentifier { return _HEMsummary; }
+(NSString *)summaryViewCellReuseIdentifier { return _HEMsummaryViewCell; }
+(NSString *)timeSliceCellReuseIdentifier { return _HEMtimeSliceCell; }
+(NSString *)titleReuseIdentifier { return _HEMtitle; }
+(NSString *)toggleReuseIdentifier { return _HEMtoggle; }
+(NSString *)welcomeReuseIdentifier { return _HEMwelcome; }

/** Segue Identifiers */
+(NSString *)alarmRepeatSegueIdentifier { return _HEMalarmRepeat; }
+(NSString *)alarmSoundsSegueIdentifier { return _HEMalarmSounds; }
+(NSString *)detailSegueIdentifier { return _HEMdetail; }
+(NSString *)expansionConfigSegueIdentifier { return _HEMexpansionConfig; }
+(NSString *)insightsSegueIdentifier { return _HEMinsights; }
+(NSString *)listSegueIdentifier { return _HEMlist; }
+(NSString *)voiceSegueIdentifier { return _HEMvoice; }

/** View Controllers */
+(id)instantiateRootViewController { return [[self storyboard] instantiateViewControllerWithIdentifier:_HEMrootViewController]; }
+(id)instantiateActionSheetViewController { return [[self storyboard] instantiateViewControllerWithIdentifier:_HEMactionSheetViewController]; }
+(id)instantiateAlarmListNavViewController { return [[self storyboard] instantiateViewControllerWithIdentifier:_HEMalarmListNavViewController]; }
+(id)instantiateAlarmListViewController { return [[self storyboard] instantiateViewControllerWithIdentifier:_HEMalarmListViewController]; }
+(id)instantiateAlarmNavController { return [[self storyboard] instantiateViewControllerWithIdentifier:_HEMalarmNavController]; }
+(id)instantiateAlarmViewController { return [[self storyboard] instantiateViewControllerWithIdentifier:_HEMalarmViewController]; }
+(id)instantiateBreakdownController { return [[self storyboard] instantiateViewControllerWithIdentifier:_HEMbreakdownController]; }
+(id)instantiateCurrentNavController { return [[self storyboard] instantiateViewControllerWithIdentifier:_HEMcurrentNavController]; }
+(id)instantiateFeedViewController { return [[self storyboard] instantiateViewControllerWithIdentifier:_HEMfeed]; }
+(id)instantiateFeedContainerViewController { return [[self storyboard] instantiateViewControllerWithIdentifier:_HEMfeedContainer]; }
+(id)instantiateInfoNavigationController { return [[self storyboard] instantiateViewControllerWithIdentifier:_HEMinfoNavigationController]; }
+(id)instantiateInfoViewController { return [[self storyboard] instantiateViewControllerWithIdentifier:_HEMinfoViewController]; }
+(id)instantiateInsightsFeedViewController { return [[self storyboard] instantiateViewControllerWithIdentifier:_HEMinsightsFeed]; }
+(id)instantiateListItemViewController { return [[self storyboard] instantiateViewControllerWithIdentifier:_HEMlistItem]; }
+(id)instantiateSleepGraphController { return [[self storyboard] instantiateViewControllerWithIdentifier:_HEMsleepGraphController]; }
+(id)instantiateSleepHistoryController { return [[self storyboard] instantiateViewControllerWithIdentifier:_HEMsleepHistoryController]; }
+(id)instantiateSleepInsightViewController { return [[self storyboard] instantiateViewControllerWithIdentifier:_HEMsleepInsight]; }
+(id)instantiateSleepQuestionsViewController { return [[self storyboard] instantiateViewControllerWithIdentifier:_HEMsleepQuestions]; }
+(id)instantiateSleepSoundViewController { return [[self storyboard] instantiateViewControllerWithIdentifier:_HEMsleepSound]; }
+(id)instantiateSlideContainerViewController { return [[self storyboard] instantiateViewControllerWithIdentifier:_HEMslideContainer]; }
+(id)instantiateSoundsNavigationViewController { return [[self storyboard] instantiateViewControllerWithIdentifier:_HEMsoundsNavigation]; }
+(id)instantiateTimelineFeedbackViewController { return [[self storyboard] instantiateViewControllerWithIdentifier:_HEMtimelineFeedback]; }
+(id)instantiateTrendsViewController { return [[self storyboard] instantiateViewControllerWithIdentifier:_HEMtrends]; }
+(id)instantiateTutorialViewController { return [[self storyboard] instantiateViewControllerWithIdentifier:_HEMtutorialViewController]; }
+(id)instantiateVoiceViewController { return [[self storyboard] instantiateViewControllerWithIdentifier:_HEMvoice]; }

@end
