//
// HEMMainStoryboard.h
// Copyright (c) 2014 Hello Inc. All rights reserved.
// Generated by Ovaltine - http://github.com/kattrali/ovaltine

#import <Foundation/Foundation.h>

@interface HEMMainStoryboard : NSObject

+(UIStoryboard *)storyboard;

/** Cell Reuse Identifiers */
+(NSString *)sleepSoundCellReuseIdentifier;
+(NSString *)infoReuseIdentifier;
+(NSString *)currentConditionsCellReuseIdentifier;
+(NSString *)alarmListCellIdentifier;
+(NSString *)alarmChoiceCellReuseIdentifier;
+(NSString *)timeSliceCellReuseIdentifier;
+(NSString *)insightCellReuseIdentifier;
+(NSString *)deviceCellReuseIdentifier;
+(NSString *)pillInfoCellReuseIdentifier;
+(NSString *)senseInfoCellReuseIdentifier;
+(NSString *)firmwareUpdateCellReuseIdentifier;
+(NSString *)settingsCellReuseIdentifier;

/** Segue Identifiers */
+(NSString *)pickSoundSegueSegueIdentifier;
+(NSString *)alarmRepeatSegueIdentifier;
+(NSString *)pillSegueIdentifier;
+(NSString *)senseSegueIdentifier;
+(NSString *)infoSettingsSegueIdentifier;
+(NSString *)unitsSettingsSegueIdentifier;
+(NSString *)devicesSegueIdentifier;


/** View Controllers */
+(UIViewController *)instantiateAlarmViewController;
+(UIViewController *)instantiateSettingsController;
+(UIViewController *)instantiateSleepQuestionsViewController;
+(UIViewController *)instantiateSensorViewController;
+(UIViewController *)instantiateCurrentController;
+(UIViewController *)instantiateAlarmListViewController;
+(UIViewController *)instantiateAlarmSoundTableViewController;
+(UIViewController *)instantiateSleepGraphController;
+(UIViewController *)instantiateSleepHistoryController;
+(UIViewController *)instantiateCurrentNavController;
+(UIViewController *)instantiateSettingsNavController;
+(UIViewController *)instantiateSleepGraphNavController;
+(UIViewController *)instantiateAlarmRepeatTableViewController;

@end
