//
// HEMMainStoryboard.h
// Copyright (c) 2015 Hello Inc. All rights reserved.
// Generated by Ovaltine - http://github.com/kattrali/ovaltine

#import <Foundation/Foundation.h>

@interface HEMMainStoryboard : NSObject

+(UIStoryboard *)storyboard;

/** Cell Reuse Identifiers */
+(NSString *)alarmSwitchCellReuseIdentifier;
+(NSString *)alarmSoundCellReuseIdentifier;
+(NSString *)alarmRepeatCellReuseIdentifier;
+(NSString *)alarmDeleteCellReuseIdentifier;
+(NSString *)singleReuseIdentifier;
+(NSString *)multipleReuseIdentifier;
+(NSString *)preferenceReuseIdentifier;
+(NSString *)imageReuseIdentifier;
+(NSString *)textReuseIdentifier;
+(NSString *)optionReuseIdentifier;
+(NSString *)infoCellReuseIdentifier;
+(NSString *)infoReuseIdentifier;
+(NSString *)explanationReuseIdentifier;
+(NSString *)signoutReuseIdentifier;
+(NSString *)unitCellReuseIdentifier;
+(NSString *)settingsCellReuseIdentifier;
+(NSString *)pairReuseIdentifier;
+(NSString *)deviceReuseIdentifier;
+(NSString *)supportCellReuseIdentifier;
+(NSString *)topicCellReuseIdentifier;
+(NSString *)warningReuseIdentifier;
+(NSString *)actionsReuseIdentifier;
+(NSString *)timezoneReuseIdentifier;
+(NSString *)choiceCellReuseIdentifier;
+(NSString *)alarmListCellReuseIdentifier;
+(NSString *)alarmListEmptyCellReuseIdentifier;
+(NSString *)alarmListStatusCellReuseIdentifier;
+(NSString *)alarmChoiceCellReuseIdentifier;
+(NSString *)sensorGraphCellReuseIdentifier;
+(NSString *)timeSliceCellReuseIdentifier;
+(NSString *)overTimeReuseIdentifier;
+(NSString *)trendGraphReuseIdentifier;
+(NSString *)questionReuseIdentifier;
+(NSString *)insightReuseIdentifier;
+(NSString *)summaryViewCellReuseIdentifier;
+(NSString *)breakdownLineCellReuseIdentifier;
+(NSString *)fieldCellReuseIdentifier;

/** Segue Identifiers */
+(NSString *)accountSettingsSegueIdentifier;
+(NSString *)alarmRepeatSegueIdentifier;
+(NSString *)choiceSegueIdentifier;
+(NSString *)devicesSettingsSegueIdentifier;
+(NSString *)notificationSettingsSegueIdentifier;
+(NSString *)pickSoundSegueIdentifier;
+(NSString *)pillSegueIdentifier;
+(NSString *)senseSegueIdentifier;
+(NSString *)settingsToSupportSegueIdentifier;
+(NSString *)timezoneSegueIdentifier;
+(NSString *)topicsSegueIdentifier;
+(NSString *)unitsSettingsSegueIdentifier;
+(NSString *)updateAccountInfoSegueIdentifier;

/** View Controllers */
+(id)instantiateRootViewController;
+(id)instantiateActionSheetViewController;
+(id)instantiateAlarmListNavViewController;
+(id)instantiateAlarmListViewController;
+(id)instantiateAlarmNavController;
+(id)instantiateAlarmRepeatTableViewController;
+(id)instantiateAlarmViewController;
+(id)instantiateBreakdownController;
+(id)instantiateCurrentNavController;
+(id)instantiateInfoNavigationController;
+(id)instantiateInfoViewController;
+(id)instantiateInsightFeedViewController;
+(id)instantiateSensorViewController;
+(id)instantiateSettingsController;
+(id)instantiateSettingsNavController;
+(id)instantiateSleepGraphController;
+(id)instantiateSleepHistoryController;
+(id)instantiateSleepInsightViewController;
+(id)instantiateSleepQuestionsViewController;
+(id)instantiateSupportTopicsViewController;
+(id)instantiateTimeZoneNavViewController;
+(id)instantiateTimeZoneViewController;
+(id)instantiateTimelineContainerController;
+(id)instantiateTimelineFeedbackViewController;
+(id)instantiateTrendsViewController;
+(id)instantiateTutorialViewController;

@end
