//
// HEMSettingsStoryboard.m
// Copyright (c) 2016 Hello Inc. All rights reserved.
// Generated by Ovaltine - http://github.com/kattrali/ovaltine

#import <UIKit/UIKit.h>
#import "HEMSettingsStoryboard.h"

static UIStoryboard *_storyboard = nil;
static NSString *const _HEMsettings = @"Settings";
static NSString *const _HEMaccountSettings = @"accountSettings";
static NSString *const _HEMaction = @"action";
static NSString *const _HEMconfig = @"config";
static NSString *const _HEMconnect = @"connect";
static NSString *const _HEMconnection = @"connection";
static NSString *const _HEMdevicesSettings = @"devicesSettings";
static NSString *const _HEMerror = @"error";
static NSString *const _HEMexpansion = @"expansion";
static NSString *const _HEMexpansionConfig = @"expansionConfig";
static NSString *const _HEMexpansionController = @"expansionController";
static NSString *const _HEMexpansions = @"expansions";
static NSString *const _HEMexplanation = @"explanation";
static NSString *const _HEMfield = @"field";
static NSString *const _HEMformViewController = @"formViewController";
static NSString *const _HEMinfo = @"info";
static NSString *const _HEMnotificationSettings = @"notificationSettings";
static NSString *const _HEMpair = @"pair";
static NSString *const _HEMpill = @"pill";
static NSString *const _HEMplain = @"plain";
static NSString *const _HEMpreference = @"preference";
static NSString *const _HEMsense = @"sense";
static NSString *const _HEMsettingsCell = @"settingsCell";
static NSString *const _HEMsettingsController = @"settingsController";
static NSString *const _HEMsettingsNavController = @"settingsNavController";
static NSString *const _HEMsettingsToSupport = @"settingsToSupport";
static NSString *const _HEMsignout = @"signout";
static NSString *const _HEMsupportCell = @"supportCell";
static NSString *const _HEMsupportTopicsViewController = @"supportTopicsViewController";
static NSString *const _HEMswitch = @"switch";
static NSString *const _HEMtext = @"text";
static NSString *const _HEMtimeZoneNavViewController = @"timeZoneNavViewController";
static NSString *const _HEMtimeZoneViewController = @"timeZoneViewController";
static NSString *const _HEMtimezone = @"timezone";
static NSString *const _HEMtoggle = @"toggle";
static NSString *const _HEMtopicCell = @"topicCell";
static NSString *const _HEMtopics = @"topics";
static NSString *const _HEMunitCell = @"unitCell";
static NSString *const _HEMunitPreference = @"unitPreference";
static NSString *const _HEMunits = @"units";
static NSString *const _HEMupdateAccountInfo = @"updateAccountInfo";
static NSString *const _HEMvoice = @"voice";
static NSString *const _HEMvoiceSettingCell = @"voiceSettingCell";
static NSString *const _HEMvolume = @"volume";
static NSString *const _HEMwarning = @"warning";

@implementation HEMSettingsStoryboard

+(UIStoryboard *)storyboard { return _storyboard ?: (_storyboard = [UIStoryboard storyboardWithName:_HEMsettings bundle:[NSBundle mainBundle]]); }

/** Cell Reuse Identifiers */
+(NSString *)actionReuseIdentifier { return _HEMaction; }
+(NSString *)configReuseIdentifier { return _HEMconfig; }
+(NSString *)connectionReuseIdentifier { return _HEMconnection; }
+(NSString *)errorReuseIdentifier { return _HEMerror; }
+(NSString *)expansionReuseIdentifier { return _HEMexpansion; }
+(NSString *)explanationReuseIdentifier { return _HEMexplanation; }
+(NSString *)fieldReuseIdentifier { return _HEMfield; }
+(NSString *)infoReuseIdentifier { return _HEMinfo; }
+(NSString *)pairReuseIdentifier { return _HEMpair; }
+(NSString *)pillReuseIdentifier { return _HEMpill; }
+(NSString *)plainReuseIdentifier { return _HEMplain; }
+(NSString *)preferenceReuseIdentifier { return _HEMpreference; }
+(NSString *)senseReuseIdentifier { return _HEMsense; }
+(NSString *)settingsCellReuseIdentifier { return _HEMsettingsCell; }
+(NSString *)signoutReuseIdentifier { return _HEMsignout; }
+(NSString *)supportCellReuseIdentifier { return _HEMsupportCell; }
+(NSString *)switchReuseIdentifier { return _HEMswitch; }
+(NSString *)textReuseIdentifier { return _HEMtext; }
+(NSString *)timezoneReuseIdentifier { return _HEMtimezone; }
+(NSString *)toggleReuseIdentifier { return _HEMtoggle; }
+(NSString *)topicCellReuseIdentifier { return _HEMtopicCell; }
+(NSString *)unitCellReuseIdentifier { return _HEMunitCell; }
+(NSString *)voiceSettingCellReuseIdentifier { return _HEMvoiceSettingCell; }
+(NSString *)warningReuseIdentifier { return _HEMwarning; }

/** Segue Identifiers */
+(NSString *)accountSettingsSegueIdentifier { return _HEMaccountSettings; }
+(NSString *)connectSegueIdentifier { return _HEMconnect; }
+(NSString *)devicesSettingsSegueIdentifier { return _HEMdevicesSettings; }
+(NSString *)expansionSegueIdentifier { return _HEMexpansion; }
+(NSString *)expansionsSegueIdentifier { return _HEMexpansions; }
+(NSString *)notificationSettingsSegueIdentifier { return _HEMnotificationSettings; }
+(NSString *)pillSegueIdentifier { return _HEMpill; }
+(NSString *)senseSegueIdentifier { return _HEMsense; }
+(NSString *)settingsToSupportSegueIdentifier { return _HEMsettingsToSupport; }
+(NSString *)timezoneSegueIdentifier { return _HEMtimezone; }
+(NSString *)topicsSegueIdentifier { return _HEMtopics; }
+(NSString *)unitsSegueIdentifier { return _HEMunits; }
+(NSString *)updateAccountInfoSegueIdentifier { return _HEMupdateAccountInfo; }
+(NSString *)voiceSegueIdentifier { return _HEMvoice; }
+(NSString *)volumeSegueIdentifier { return _HEMvolume; }

/** View Controllers */
+(id)instantiateExpansionConfigViewController { return [[self storyboard] instantiateViewControllerWithIdentifier:_HEMexpansionConfig]; }
+(id)instantiateExpansionController { return [[self storyboard] instantiateViewControllerWithIdentifier:_HEMexpansionController]; }
+(id)instantiateFormViewController { return [[self storyboard] instantiateViewControllerWithIdentifier:_HEMformViewController]; }
+(id)instantiateSettingsController { return [[self storyboard] instantiateViewControllerWithIdentifier:_HEMsettingsController]; }
+(id)instantiateSettingsNavController { return [[self storyboard] instantiateViewControllerWithIdentifier:_HEMsettingsNavController]; }
+(id)instantiateSupportTopicsViewController { return [[self storyboard] instantiateViewControllerWithIdentifier:_HEMsupportTopicsViewController]; }
+(id)instantiateTimeZoneNavViewController { return [[self storyboard] instantiateViewControllerWithIdentifier:_HEMtimeZoneNavViewController]; }
+(id)instantiateTimeZoneViewController { return [[self storyboard] instantiateViewControllerWithIdentifier:_HEMtimeZoneViewController]; }
+(id)instantiateUnitPreferenceViewController { return [[self storyboard] instantiateViewControllerWithIdentifier:_HEMunitPreference]; }

@end
